name: Build exe with Poetry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
      
    - name: Install Poetry
      uses: snok/install-poetry@v1
      
    - name: Install dependencies
      run: poetry install
      
    - name: Build exe
      run: poetry run pyinstaller -- $GITHUB_ACTION_PATH/src/gui/__main__.py
      
    - name: Upload exe artifact
      uses: actions/upload-artifact@v2
      with:
        name: exe-artifact
        path: dist/$GITHUB_ACTION_PATH/src/gui/__main__.exe
