name: Build exe with Poetry

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
      
    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Installing Poetry via pip
      run: |
        python -m pip install --user pipx
        pipx install poetry
      
    - name: Install dependencies
      run: |
        poetry install
      
    - name: Build exe
      run: poetry run pyinstaller src/gui/__main__.py --collect-all scienceplots --onefile --name main
      
    - name: Upload exe artifact
      uses: actions/upload-artifact@v4
      with:
        name: main
        path: D:\a\solid-state_kinetics\solid-state_kinetics\dist\main.exe
        
    - name: Release
      uses: fnkr/github-action-ghr@v1
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GHR_COMPRESS: zip
        GHR_PATH: D:\a\solid-state_kinetics\solid-state_kinetics\dist\main.exe
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
