name: Build exe with Poetry

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build for ${{ matrix.os }}
    runs-on: windows-latest
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: main
          - os: windows-latest
            artifact_name: main.exe
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
  
      - name: Installing Poetry via pip
        run: |
          python -m pip install --user pipx
          pipx install poetry
          poetry install
            
      - name: Build
        run: poetry run pyinstaller src/gui/__main__.py --collect-all scienceplots --onefile --name main

      
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: main
          path: dist/${{ matrix.artifact_name }}
        

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: dist/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
